name: Generate OpenAPI pages

on:
  push:
    paths:
      - "openapi-specs/**"

jobs:
  run-scraping:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Run pnpx @mintlify/scraping
        run: pnpx @mintlify/scraping@latest openapi-file openapi-specs/openapi.documented.json -o api-reference

      - uses: stefanzweifel/git-auto-commit-action@v5
